#!/usr/bin/env ruby

# TODO: Remove this line. http://guides.rubygems.org/patterns/
$LOAD_PATH.unshift(File.dirname(__FILE__) + '/../lib')

require 'letsencrypt_webfaction/application'

LetsencryptWebfaction::Application.new.run!
